title: Alan Marcell
email: alanmarcell@live.com
description: A passionate programer who loves to learn
theme: jekyll-theme-cayman
logo: /assets/pic.jpeg

github_username: alanmarcell

markdown: kramdown
permalink: pretty
